export const featureCopyAm: Record<string, string> = {
  "Samra Pay Card Portfolio — Coming Soon": "የSamra Pay ካርድ ስብስብ — በቅርቡ",
  "Card portfolio · Coming soon": "የካርድ ስብስብ · በቅርቡ",
  "Start with credit building. Move into everyday rewards. Unlock more cross-border value—and recognize the first members helping shape Samra.": "የክሬዲት ታሪክን በማጠናከር ይጀምሩ። ወደ ዕለታዊ ሽልማቶች ይሂዱ። ድንበር ተሻጋሪ ዋጋን ያሳድጉ—Samraን ለመቅረጽ የሚረዱትን የመጀመሪያ አባላት ያክብሩ።",
  "All four products are in development and are not open for application.": "አራቱም ምርቶች በግንባታ ላይ ናቸው፣ ለማመልከትም ገና አልተከፈቱም።",
  "The Samra Pay card portfolio": "የSamra Pay ካርድ ስብስብ",
  "Three levels. One founding edition.": "ሦስት ደረጃዎች። አንድ የመስራች እትም።",
  "Charge, Elite, and Ethiopian Airlines form a progression. Elite 100 is a handpicked Alpha edition with separate terms.": "Charge፣ Elite እና Ethiopian Airlines ተከታታይ ደረጃዎችን ይፈጥራሉ። Elite 100 በተለየ ውል የተመረጡ የAlpha አባላት እትም ነው።",
  "Founding edition": "የመስራች እትም",
  "Invitation only": "በግብዣ ብቻ",
  "Coming soon": "በቅርቡ",
  "Charge": "Charge",
  "Elite": "Elite",
  "Co-branded": "የጋራ ብራንድ",
  "Elite 100": "Elite 100",
  "Everyday ShebaMiles": "ዕለታዊ ShebaMiles",
  "2X ShebaMiles": "2X ShebaMiles",
  "Titanium founding edition": "የቲታኒየም መስራች እትም",
  "Level 04 · Titanium edition": "ደረጃ 04 · የቲታኒየም እትም",
  "Elite 100 details": "የElite 100 ዝርዝሮች",
  "Member since 2026": "ከ2026 ጀምሮ አባል",
  "Titanium": "ቲታኒየም",
  "Limited serial": "የተወሰነ ቁጥር",
  "Material": "ቁሳቁስ",
  "Edition": "እትም",
  "Founding 100": "የመጀመሪያ 100",
  "Member": "አባል",
  "Since 2026": "ከ2026 ጀምሮ",
  "Entry · Credit building": "መግቢያ · የክሬዲት ታሪክ ማጠናከር",
  "Build your foundation.": "መሠረትዎን ይገንቡ።",
  "A straightforward starting point designed to help eligible everyday activity support your credit journey.": "ብቁ የሆነ ዕለታዊ እንቅስቃሴ የክሬዲት ጉዞዎን እንዲደግፍ የተነደፈ ግልጽ መነሻ።",
  "Credit-building tools designed around eligible activity": "በብቁ እንቅስቃሴ ዙሪያ የተነደፉ የክሬዲት ታሪክ ማጠናከሪያ መሳሪያዎች",
  "Planned pay-in-full charge structure": "የታቀደ በሙሉ የሚከፈል charge card መዋቅር",
  "Clear balance and spending controls": "ግልጽ የቀሪ ሂሳብና የወጪ ቁጥጥር",
  "Base Samra Pay FX rate": "መሠረታዊ የSamra Pay FX ተመን",
  "Everyday rewards": "ዕለታዊ ሽልማቶች",
  "Turn everyday spend into miles.": "ዕለታዊ ወጪን ወደ miles ይቀይሩ።",
  "The next level adds proposed ShebaMiles rewards to eligible everyday purchases.": "ቀጣዩ ደረጃ ለብቁ ዕለታዊ ግዢዎች የታቀዱ የShebaMiles ሽልማቶችን ይጨምራል።",
  "Everything planned for Samra Pay Charge": "ለSamra Pay Charge የታቀደው ሁሉ",
  "Proposed ShebaMiles on eligible everyday spend": "በብቁ ዕለታዊ ወጪ የታቀዱ ShebaMiles",
  "Proposed FX benefit: +1%": "የታቀደ የFX ጥቅም፦ +1%",
  "A single view of spending, rewards, and transfers": "ወጪ፣ ሽልማቶችና ዝውውሮች በአንድ እይታ",
  "Proposed airline co-brand": "የታቀደ የአየር መንገድ የጋራ ብራንድ",
  "Go further with every purchase.": "በእያንዳንዱ ግዢ የበለጠ ይጓዙ።",
  "The highest level is envisioned as an Ethiopian Airlines co-branded card with proposed 2X ShebaMiles on eligible spend.": "ከፍተኛው ደረጃ ከEthiopian Airlines ጋር የጋራ ብራንድ ያለው፣ በብቁ ወጪ የታቀደ 2X ShebaMiles የሚሰጥ ካርድ እንዲሆን ታስቧል።",
  "Everything planned for Samra Pay Elite": "ለSamra Pay Elite የታቀደው ሁሉ",
  "Proposed 2X ShebaMiles on eligible spend": "በብቁ ወጪ የታቀደ 2X ShebaMiles",
  "Proposed FX benefit: +2%": "የታቀደ የFX ጥቅም፦ +2%",
  "Airline-linked benefits to be defined with the partner": "ከአየር መንገዱ ጋር የተገናኙ ጥቅሞች ከአጋሩ ጋር ይወሰናሉ",
  "Invitation only · Founding 100": "በግብዣ ብቻ · የመጀመሪያ 100",
  "For the first 100 who believed.": "ከመጀመሪያ ለአመኑት 100 ሰዎች።",
  "A handpicked Alpha group limited to the first 100 people who believed in Samra from the beginning.": "ከመጀመሪያ በSamra ላመኑ 100 ሰዎች ብቻ የተመረጠ የAlpha ቡድን።",
  "Handpicked Alpha membership": "የተመረጠ የAlpha አባልነት",
  "One of 100 individually numbered titanium cards": "ከ100 በተናጠል ቁጥር ከተሰጣቸው ቲታኒየም ካርዶች አንዱ",
  "Recognition as part of Samra’s first Alpha group": "የSamra የመጀመሪያ Alpha ቡድን አባል እንደመሆን እውቅና",
  "Proposed annual membership": "የታቀደ ዓመታዊ አባልነት",
  "Proposed annual ShebaMiles reward": "የታቀደ ዓመታዊ የShebaMiles ሽልማት",
  "Planned across the portfolio": "በስብስቡ ሁሉ የታቀደ",
  "More value from day one.": "ከመጀመሪያው ቀን የበለጠ ዋጋ።",
  "The portfolio is designed around these foundational features. Final availability will vary by tier, eligibility, and program terms.": "የካርድ ስብስቡ በእነዚህ መሠረታዊ ባህሪያት ዙሪያ ተነድፏል። የመጨረሻ አቅርቦት በደረጃ፣ በብቁነትና በፕሮግራም ውሎች ይለያያል።",
  "Direct deposit": "ቀጥታ ተቀማጭ",
  "Payday, up to two days early.": "የክፍያ ቀን፣ እስከ ሁለት ቀን ቀድሞ።",
  "Qualifying direct deposits may arrive up to two days before the scheduled payment date, depending on when the payer sends funds.": "ብቁ ቀጥታ ተቀማጭ ክፍያዎች ከፋዩ ገንዘቡን በሚልክበት ጊዜ መሠረት ከታቀደው ቀን እስከ ሁለት ቀን ቀድመው ሊደርሱ ይችላሉ።",
  "Credit building": "የክሬዲት ታሪክ ማጠናከር",
  "Make recurring bills count.": "ተደጋጋሚ ክፍያዎችዎን ዋጋ ያላቸው ያድርጉ።",
  "Planned reporting of eligible monthly recurring bills to participating credit bureaus, subject to enrollment and program terms.": "ብቁ ወርሃዊ ተደጋጋሚ ክፍያዎችን ለሚሳተፉ የክሬዲት ቢሮዎች ማሳወቅ ታቅዷል፤ በምዝገባና በፕሮግራም ውሎች ይገዛል።",
  "Instant access": "ፈጣን መዳረሻ",
  "A virtual card right away.": "virtual ካርድ ወዲያውኑ።",
  "Eligible customers can receive a virtual card after approval and identity verification, before the physical card arrives.": "ብቁ ደንበኞች ከፈቃድና ከማንነት ማረጋገጫ በኋላ፣ አካላዊው ካርድ ከመድረሱ በፊት virtual ካርድ ሊያገኙ ይችላሉ።",
  "Physical card": "አካላዊ ካርድ",
  "Titanium, delivered home.": "ቲታኒየም፣ ወደ ቤትዎ ይላካል።",
  "A planned titanium physical card mailed to your verified address in the United States or Canada.": "የታቀደ ቲታኒየም አካላዊ ካርድ በዩናይትድ ስቴትስ ወይም ካናዳ ወዳለው የተረጋገጠ አድራሻዎ ይላካል።",
  "Send home": "ወደ ቤት ይላኩ",
  "Our best available rate.": "ያለን ምርጥ ተመን።",
  "See the rate, fees, amount received, and delivery estimate before confirming. Instant delivery is planned where supported.": "ከማረጋገጥዎ በፊት ተመኑን፣ ክፍያዎችን፣ የሚደርሰውን መጠንና የመድረሻ ግምትን ይመልከቱ። በሚደገፍበት ቦታ ፈጣን መድረስ ታቅዷል።",
  "At a glance": "በአጭሩ",
  "Compare the portfolio.": "የካርድ ስብስቡን ያወዳድሩ።",
  "The first three cards progress from financial foundation to rewards and airline value. Elite 100 sits beside them as invitation-only Alpha access.": "የመጀመሪያዎቹ ሦስት ካርዶች ከገንዘብ መሠረት ወደ ሽልማቶችና የአየር መንገድ ዋጋ ያድጋሉ። Elite 100 ከእነሱ ጎን በግብዣ ብቻ የሚገኝ Alpha መዳረሻ ነው።",
  "Scroll horizontally to compare all four cards": "አራቱንም ካርዶች ለማወዳደር ወደ ጎን ያንሸራትቱ",
  "Samra Pay card tier comparison": "የSamra Pay የካርድ ደረጃዎች ማወዳደሪያ",
  "Scrollable card tier comparison": "ሊንሸራተት የሚችል የካርድ ደረጃ ንጽጽር",
  "Benefit": "ጥቅም",
  "Primary value": "ዋና ዋጋ",
  "Miles on eligible spend": "በብቁ ወጪ የሚገኙ miles",
  "FX benefit": "የFX ጥቅም",
  "Annual membership": "ዓመታዊ አባልነት",
  "Annual ShebaMiles reward": "ዓመታዊ የShebaMiles ሽልማት",
  "Availability": "አቅርቦት",
  "Credit-building foundation": "የክሬዲት ታሪክ መሠረት",
  "Airline rewards": "የአየር መንገድ ሽልማቶች",
  "Elite 100 recognition": "የElite 100 እውቅና",
  "Proposed ShebaMiles": "የታቀዱ ShebaMiles",
  "Proposed 2X ShebaMiles": "የታቀደ 2X ShebaMiles",
  "To be announced": "በኋላ ይገለጻል",
  "Base Samra Pay rate": "መሠረታዊ የSamra Pay ተመን",
  "Proposed +1%": "የታቀደ +1%",
  "Proposed +2%": "የታቀደ +2%",
  "Proposed $195": "የታቀደ $195",
  "Proposed $495": "የታቀደ $495",
  "Proposed 15,000": "የታቀደ 15,000",
  "Proposed 45,000": "የታቀደ 45,000",
  "Invitation only · First 100": "በግብዣ ብቻ · የመጀመሪያ 100",
  "Product status": "የምርት ሁኔታ",
  "Concept benefits, clearly labeled.": "የሀሳብ ደረጃ ጥቅሞች፣ በግልጽ የተለዩ።",
  "Samra Pay Charge, Samra Pay Elite, the proposed Ethiopian Airlines co-branded card, and the Samra Elite 100 card are product concepts in development. They are not available for application or use.": "Samra Pay Charge፣ Samra Pay Elite፣ የታቀደው የEthiopian Airlines የጋራ ብራንድ ካርድ እና Samra Elite 100 ካርድ በግንባታ ላይ ያሉ የምርት ሀሳቦች ናቸው። ለማመልከት ወይም ለመጠቀም ገና አይገኙም።",
  "ShebaMiles earning and Ethiopian Airlines co-branding depend on executed commercial and technical agreements. Final eligibility, earn rates, fees, reporting, card terms, and benefits may change.": "ShebaMiles ማግኘትና ከEthiopian Airlines ጋር የሚደረግ የጋራ ብራንድ ተፈርመው በተጠናቀቁ የንግድና የቴክኒክ ስምምነቶች ላይ ይመሰረታሉ። የመጨረሻ ብቁነት፣ የማግኛ መጠን፣ ክፍያዎች፣ ሪፖርት፣ የካርድ ውሎችና ጥቅሞች ሊለወጡ ይችላሉ።",
  "The +1% and +2% FX benefits are proposed tier uplifts. The baseline rate, calculation method, eligible transfers, limits, and final terms have not been established.": "የ+1% እና +2% FX ጥቅሞች የታቀዱ የደረጃ ጭማሪዎች ናቸው። መሠረታዊው ተመን፣ የስሌት ዘዴ፣ ብቁ ዝውውሮች፣ ገደቦችና የመጨረሻ ውሎች ገና አልተወሰኑም።",
  "Early direct deposit, recurring-bill reporting, instant virtual cards, titanium cards, and instant transfers are proposed features. Availability depends on issuing, bureau reporting, identity, address, corridor, and payment-method eligibility. “Best available rate” refers to the eligible Samra Pay rate presented for a transaction, not a guaranteed market-best rate.": "ቀድሞ የሚደርስ ቀጥታ ተቀማጭ፣ ተደጋጋሚ ክፍያዎችን ሪፖርት ማድረግ፣ ፈጣን virtual ካርዶች፣ ቲታኒየም ካርዶችና ፈጣን ዝውውሮች የታቀዱ ባህሪያት ናቸው። አቅርቦታቸው በካርድ አወጣጥ፣ በክሬዲት ቢሮ ሪፖርት፣ በማንነት፣ በአድራሻ፣ በዝውውር መስመርና በክፍያ ዘዴ ብቁነት ላይ ይመሰረታል። “ያለን ምርጥ ተመን” ማለት ለግብይቱ የሚቀርበውን ብቁ የSamra Pay ተመን ነው፤ ከገበያ ሁሉ የተሻለ ተመን ዋስትና አይደለም።",
  "The proposed $195 Elite membership, $495 Ethiopian Airlines-tier membership, and annual rewards of 15,000 and 45,000 ShebaMiles are not final. Qualification, award timing, renewal eligibility, taxes, fees, miles expiration, and final terms have not been established.": "የታቀደው $195 Elite አባልነት፣ $495 የEthiopian Airlines ደረጃ አባልነት እና ዓመታዊ 15,000 እና 45,000 ShebaMiles ሽልማቶች የመጨረሻ አይደሉም። ብቁነት፣ የሽልማት ጊዜ፣ የእድሳት ብቁነት፣ ግብሮች፣ ክፍያዎች፣ የmiles ማብቂያና የመጨረሻ ውሎች ገና አልተወሰኑም።",
  "Samra Elite 100 is a proposed, invitation-only Alpha designation limited to 100 founder-selected members. Pricing, rewards, access, final benefits, and card issuance have not been established, and no Elite 100 cards are currently available.": "Samra Elite 100 በመስራቹ ለተመረጡ 100 አባላት ብቻ በግብዣ የሚቀርብ የAlpha ስያሜ እንዲሆን ታቅዷል። ዋጋ፣ ሽልማቶች፣ መዳረሻ፣ የመጨረሻ ጥቅሞችና የካርድ አወጣጥ ገና አልተወሰኑም፣ ምንም Elite 100 ካርድም አሁን አይገኝም።",
  "The first chapter": "የመጀመሪያው ምዕራፍ",
  "Built for progress. Marked by belief.": "ለእድገት የተገነባ። በእምነት የተለየ።",
  "Limited Alpha is planned for the United States and Canada in April 2027.": "የተወሰነ Alpha በአሜሪካና ካናዳ ለApril 2027 ታቅዷል።",
  "View development status": "የግንባታ ሁኔታን ይመልከቱ",
  "Card portfolio pillars": "የካርድ ስብስቡ ዋና መሠረቶች",
  "Credit": "ክሬዲት",
  "FX value": "የFX ዋጋ",
  "Miles": "Miles",
};
