// Synthetic fixture data for mock mode.
// ALL financial values are decimal strings from this file — never computed.
// Clearly labeled as synthetic in the UI via IS_MOCK + data-mode banner.

import type {
  Customer,
  Transfer,
  MoneyFlow,
  ReconciliationRun,
  WorkerJob,
  AuditEvent,
  SystemHealth,
  AggregateReport,
  OpsMetric,
} from './types';

// ─── Overview Metrics ────────────────────────────────────────────────────────

export const OVERVIEW_METRICS: OpsMetric[] = [
  {
    source: 'ledger',
    label: 'Total Transfer Volume (24h)',
    value: '4,821,330.00',
    unit: 'USD',
    delta: '+12.4%',
    deltaDirection: 'up',
  },
  {
    source: 'ledger',
    label: 'Completed Transfers (24h)',
    value: '2,347',
    unit: 'transfers',
    delta: '+8.1%',
    deltaDirection: 'up',
  },
  {
    source: 'ledger',
    label: 'Failed Transfers (24h)',
    value: '43',
    unit: 'transfers',
    delta: '-2.3%',
    deltaDirection: 'down',
  },
  {
    source: 'provider',
    label: 'Provider Settlement Pending',
    value: '182,400.00',
    unit: 'USD',
    delta: 'neutral',
    deltaDirection: 'neutral',
  },
  {
    source: 'ledger',
    label: 'Reconciliation Exceptions',
    value: '7',
    unit: 'open',
    delta: '+2',
    deltaDirection: 'up',
  },
  {
    source: 'cache',
    label: 'Active Worker Jobs',
    value: '14',
    unit: 'running',
    deltaDirection: 'neutral',
  },
];

// ─── Customers ────────────────────────────────────────────────────────────────

export const CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    externalRef: 'EXT-20240115-ABCD',
    displayName: 'Synthetic customer C-001',
    status: 'active',
    kycTier: 2,
    registeredAt: '2023-06-01T09:12:00Z',
    accounts: [
      {
        id: 'acct-001a',
        reference: 'ACCT-USD-00142',
        currency: 'USD',
        bookBalance: '3,420.00',
        availableBalance: '3,220.00',
        heldBalance: '200.00',
        openedAt: '2023-06-01T09:14:00Z',
      },
      {
        id: 'acct-001b',
        reference: 'ACCT-ETB-00143',
        currency: 'ETB',
        bookBalance: '84,500.00',
        availableBalance: '84,500.00',
        heldBalance: '0.00',
        openedAt: '2023-06-01T09:14:30Z',
      },
    ],
    recentTransferIds: ['txn-001', 'txn-003'],
    issues: [],
  },
  {
    id: 'cust-002',
    externalRef: 'EXT-20240220-EFGH',
    displayName: 'Synthetic customer C-002',
    status: 'suspended',
    kycTier: 1,
    registeredAt: '2024-02-20T14:55:00Z',
    accounts: [
      {
        id: 'acct-002a',
        reference: 'ACCT-USD-00289',
        currency: 'USD',
        bookBalance: '0.00',
        availableBalance: '0.00',
        heldBalance: '500.00',
        openedAt: '2024-02-20T14:57:00Z',
      },
    ],
    recentTransferIds: ['txn-004'],
    issues: [
      {
        level: 'error',
        code: 'KYC_HOLD',
        message: 'Account suspended pending KYC tier 2 upgrade.',
        raisedAt: '2024-03-01T08:00:00Z',
      },
    ],
  },
  {
    id: 'cust-003',
    externalRef: 'EXT-20231101-IJKL',
    displayName: 'Synthetic customer C-003',
    status: 'active',
    kycTier: 3,
    registeredAt: '2023-11-01T11:00:00Z',
    accounts: [
      {
        id: 'acct-003a',
        reference: 'ACCT-USD-00051',
        currency: 'USD',
        bookBalance: '12,000.00',
        availableBalance: '11,750.00',
        heldBalance: '250.00',
        openedAt: '2023-11-01T11:05:00Z',
      },
    ],
    recentTransferIds: ['txn-002', 'txn-005'],
    issues: [
      {
        level: 'warning',
        code: 'HIGH_VELOCITY',
        message: '5 transfers in 6 hours — velocity check flagged.',
        raisedAt: '2024-06-14T07:30:00Z',
      },
    ],
  },
  {
    id: 'cust-004',
    externalRef: 'EXT-20240310-MNOP',
    displayName: 'Synthetic customer C-004',
    status: 'pending_kyc',
    kycTier: 0,
    registeredAt: '2024-03-10T16:20:00Z',
    accounts: [],
    recentTransferIds: [],
    issues: [
      {
        level: 'info',
        code: 'KYC_PENDING',
        message: 'KYC documents submitted, awaiting review.',
        raisedAt: '2024-03-10T16:25:00Z',
      },
    ],
  },
];

// ─── Transfers ────────────────────────────────────────────────────────────────

export const TRANSFERS: Transfer[] = [
  {
    id: 'txn-001',
    reference: 'TXN-20240614-001',
    senderId: 'cust-001',
    senderName: 'Synthetic customer C-001',
    recipientId: undefined,
    recipientName: 'Synthetic beneficiary B-001',
    sendAmount: { amount: '500.00', currency: 'USD' },
    receiveAmount: { amount: '27,500.00', currency: 'ETB' },
    fee: { amount: '4.50', currency: 'USD' },
    exchangeRate: '55.00',
    status: 'completed',
    fundingState: 'settled',
    payoutState: 'delivered',
    reconciliationState: 'matched',
    providerRef: 'PRV-ETHSWIFT-20240614-7821',
    providerCorrelationRef: 'CORR-7821-AB',
    createdAt: '2024-06-14T08:00:00Z',
    updatedAt: '2024-06-14T08:12:30Z',
    completedAt: '2024-06-14T08:12:30Z',
    timeline: [
      {
        id: 'tl-001-1',
        timestamp: '2024-06-14T08:00:00Z',
        category: 'samra_canonical',
        label: 'Transfer Initiated',
        detail: 'Transfer record created in Samra ledger.',
      },
      {
        id: 'tl-001-2',
        timestamp: '2024-06-14T08:00:45Z',
        category: 'samra_canonical',
        label: 'Funding Captured',
        detail: 'USD 500.00 debited from sender account ACCT-USD-00142.',
      },
      {
        id: 'tl-001-3',
        timestamp: '2024-06-14T08:01:10Z',
        category: 'worker',
        label: 'Payout Job Enqueued',
        detail: 'Worker payout-delivery queued job ID wrk-9921.',
      },
      {
        id: 'tl-001-4',
        timestamp: '2024-06-14T08:03:00Z',
        category: 'provider_evidence',
        label: 'Provider Acknowledged',
        detail: 'EthSwift confirmed receipt.',
        correlationRef: 'CORR-7821-AB',
      },
      {
        id: 'tl-001-5',
        timestamp: '2024-06-14T08:12:30Z',
        category: 'provider_evidence',
        label: 'Provider Delivered',
        detail: 'ETB 27,500.00 credited at destination. Provider ref PRV-ETHSWIFT-20240614-7821.',
        correlationRef: 'PRV-ETHSWIFT-20240614-7821',
      },
      {
        id: 'tl-001-6',
        timestamp: '2024-06-14T08:12:35Z',
        category: 'samra_canonical',
        label: 'Transfer Completed',
        detail: 'Samra ledger marked complete. Reconciliation matched.',
      },
    ],
  },
  {
    id: 'txn-002',
    reference: 'TXN-20240614-002',
    senderId: 'cust-003',
    senderName: 'Synthetic customer C-003',
    recipientName: 'Synthetic beneficiary B-002',
    sendAmount: { amount: '1,200.00', currency: 'USD' },
    receiveAmount: { amount: '66,000.00', currency: 'ETB' },
    fee: { amount: '9.00', currency: 'USD' },
    exchangeRate: '55.00',
    status: 'pending',
    fundingState: 'captured',
    payoutState: 'processing',
    reconciliationState: 'pending',
    providerRef: 'PRV-ETHSWIFT-20240614-7822',
    createdAt: '2024-06-14T09:30:00Z',
    updatedAt: '2024-06-14T09:45:00Z',
    timeline: [
      {
        id: 'tl-002-1',
        timestamp: '2024-06-14T09:30:00Z',
        category: 'samra_canonical',
        label: 'Transfer Initiated',
        detail: 'Transfer record created.',
      },
      {
        id: 'tl-002-2',
        timestamp: '2024-06-14T09:30:50Z',
        category: 'samra_canonical',
        label: 'Funding Captured',
        detail: 'USD 1,200.00 debited from ACCT-USD-00051.',
      },
      {
        id: 'tl-002-3',
        timestamp: '2024-06-14T09:32:00Z',
        category: 'provider_evidence',
        label: 'Provider Acknowledged',
        detail: 'EthSwift accepted payout request.',
        correlationRef: 'PRV-ETHSWIFT-20240614-7822',
      },
    ],
  },
  {
    id: 'txn-003',
    reference: 'TXN-20240613-089',
    senderId: 'cust-001',
    senderName: 'Synthetic customer C-001',
    recipientName: 'Synthetic beneficiary B-003',
    sendAmount: { amount: '250.00', currency: 'USD' },
    receiveAmount: { amount: '13,750.00', currency: 'ETB' },
    fee: { amount: '3.00', currency: 'USD' },
    exchangeRate: '55.00',
    status: 'failed',
    fundingState: 'refunded',
    payoutState: 'failed',
    reconciliationState: 'matched',
    providerRef: 'PRV-ETHSWIFT-20240613-6601',
    createdAt: '2024-06-13T14:00:00Z',
    updatedAt: '2024-06-13T14:08:00Z',
    timeline: [
      {
        id: 'tl-003-1',
        timestamp: '2024-06-13T14:00:00Z',
        category: 'samra_canonical',
        label: 'Transfer Initiated',
        detail: 'Transfer record created.',
      },
      {
        id: 'tl-003-2',
        timestamp: '2024-06-13T14:00:45Z',
        category: 'samra_canonical',
        label: 'Funding Captured',
        detail: 'USD 250.00 debited.',
      },
      {
        id: 'tl-003-3',
        timestamp: '2024-06-13T14:03:00Z',
        category: 'provider_evidence',
        label: 'Provider Rejected',
        detail: 'EthSwift: destination account not found. Code: ACCT_NOT_FOUND.',
        correlationRef: 'PRV-ETHSWIFT-20240613-6601',
      },
      {
        id: 'tl-003-4',
        timestamp: '2024-06-13T14:05:00Z',
        category: 'samra_canonical',
        label: 'Transfer Failed',
        detail: 'Samra canonical state set to failed.',
      },
      {
        id: 'tl-003-5',
        timestamp: '2024-06-13T14:08:00Z',
        category: 'samra_canonical',
        label: 'Funding Refunded',
        detail: 'USD 250.00 + USD 3.00 fee returned to sender ledger.',
      },
    ],
  },
  {
    id: 'txn-004',
    reference: 'TXN-20240612-041',
    senderId: 'cust-002',
    senderName: 'Synthetic customer C-002',
    recipientName: 'Synthetic beneficiary B-004',
    sendAmount: { amount: '750.00', currency: 'USD' },
    receiveAmount: { amount: '41,250.00', currency: 'ETB' },
    fee: { amount: '6.00', currency: 'USD' },
    exchangeRate: '55.00',
    status: 'reconciliation_exception',
    fundingState: 'settled',
    payoutState: 'delivered',
    reconciliationState: 'exception',
    providerRef: 'PRV-ETHSWIFT-20240612-5501',
    providerCorrelationRef: 'CORR-5501-CD',
    createdAt: '2024-06-12T11:00:00Z',
    updatedAt: '2024-06-12T11:20:00Z',
    completedAt: '2024-06-12T11:18:00Z',
    timeline: [
      {
        id: 'tl-004-1',
        timestamp: '2024-06-12T11:00:00Z',
        category: 'samra_canonical',
        label: 'Transfer Initiated',
        detail: 'Transfer record created.',
      },
      {
        id: 'tl-004-2',
        timestamp: '2024-06-12T11:01:00Z',
        category: 'samra_canonical',
        label: 'Funding Captured',
        detail: 'USD 750.00 debited.',
      },
      {
        id: 'tl-004-3',
        timestamp: '2024-06-12T11:05:00Z',
        category: 'provider_evidence',
        label: 'Provider Delivered',
        detail: 'EthSwift reported ETB 41,000.00 delivered (expected 41,250.00).',
        correlationRef: 'CORR-5501-CD',
      },
      {
        id: 'tl-004-4',
        timestamp: '2024-06-12T11:18:00Z',
        category: 'samra_canonical',
        label: 'Reconciliation Exception Raised',
        detail: 'Amount mismatch: Samra ETB 41,250.00 vs provider ETB 41,000.00.',
      },
    ],
  },
  {
    id: 'txn-005',
    reference: 'TXN-20240614-003',
    senderId: 'cust-003',
    senderName: 'Synthetic customer C-003',
    recipientName: 'Synthetic beneficiary B-005',
    sendAmount: { amount: '300.00', currency: 'USD' },
    receiveAmount: { amount: '16,500.00', currency: 'ETB' },
    fee: { amount: '3.50', currency: 'USD' },
    exchangeRate: '55.00',
    status: 'timed_out',
    fundingState: 'refunded',
    payoutState: 'failed',
    reconciliationState: 'skipped',
    providerRef: 'PRV-ETHSWIFT-20240614-7900',
    createdAt: '2024-06-14T06:00:00Z',
    updatedAt: '2024-06-14T06:35:00Z',
    timeline: [
      {
        id: 'tl-005-1',
        timestamp: '2024-06-14T06:00:00Z',
        category: 'samra_canonical',
        label: 'Transfer Initiated',
        detail: 'Transfer record created.',
      },
      {
        id: 'tl-005-2',
        timestamp: '2024-06-14T06:00:45Z',
        category: 'samra_canonical',
        label: 'Funding Captured',
        detail: 'USD 300.00 debited.',
      },
      {
        id: 'tl-005-3',
        timestamp: '2024-06-14T06:35:00Z',
        category: 'system',
        label: 'Payout Timeout',
        detail: 'No provider confirmation received within 35-minute SLA window.',
      },
      {
        id: 'tl-005-4',
        timestamp: '2024-06-14T06:35:05Z',
        category: 'samra_canonical',
        label: 'Transfer Timed Out',
        detail: 'Samra canonical state set to timed_out. Refund initiated.',
      },
    ],
  },
  {
    id: 'txn-006',
    reference: 'TXN-20240611-003',
    senderId: 'cust-001',
    senderName: 'Synthetic customer C-001',
    recipientName: 'Synthetic beneficiary B-006',
    sendAmount: { amount: '100.00', currency: 'USD' },
    receiveAmount: { amount: '5,500.00', currency: 'ETB' },
    fee: { amount: '2.00', currency: 'USD' },
    exchangeRate: '55.00',
    status: 'reversed',
    fundingState: 'refunded',
    payoutState: 'reversed',
    reconciliationState: 'matched',
    providerRef: 'PRV-ETHSWIFT-20240611-4411',
    createdAt: '2024-06-11T10:00:00Z',
    updatedAt: '2024-06-11T12:00:00Z',
    completedAt: '2024-06-11T10:15:00Z',
    timeline: [
      {
        id: 'tl-006-1',
        timestamp: '2024-06-11T10:00:00Z',
        category: 'samra_canonical',
        label: 'Transfer Initiated',
        detail: 'Transfer record created.',
      },
      {
        id: 'tl-006-2',
        timestamp: '2024-06-11T10:15:00Z',
        category: 'samra_canonical',
        label: 'Transfer Completed',
        detail: 'Delivered and reconciled.',
      },
      {
        id: 'tl-006-3',
        timestamp: '2024-06-11T11:30:00Z',
        category: 'system',
        label: 'Reversal Requested',
        detail: 'Admin reversal request logged via audited command.',
      },
      {
        id: 'tl-006-4',
        timestamp: '2024-06-11T12:00:00Z',
        category: 'samra_canonical',
        label: 'Transfer Reversed',
        detail: 'ETB 5,500.00 recalled. USD 100.00 + fee returned to sender.',
      },
    ],
  },
  {
    id: 'txn-007',
    reference: 'TXN-20240610-028',
    senderId: 'cust-002',
    senderName: 'Synthetic customer C-002',
    recipientName: 'Synthetic beneficiary B-007',
    sendAmount: { amount: '180.00', currency: 'USD' },
    receiveAmount: { amount: '9,900.00', currency: 'ETB' },
    fee: { amount: '2.50', currency: 'USD' },
    exchangeRate: '55.00',
    status: 'refunded',
    fundingState: 'refunded',
    payoutState: 'failed',
    reconciliationState: 'matched',
    providerRef: 'PRV-ETHSWIFT-20240610-3302',
    createdAt: '2024-06-10T13:00:00Z',
    updatedAt: '2024-06-10T13:18:00Z',
    timeline: [
      {
        id: 'tl-007-1',
        timestamp: '2024-06-10T13:00:00Z',
        category: 'samra_canonical',
        label: 'Transfer Initiated',
        detail: 'Synthetic transfer record created.',
      },
      {
        id: 'tl-007-2',
        timestamp: '2024-06-10T13:04:00Z',
        category: 'provider_evidence',
        label: 'Provider Rejected',
        detail: 'Synthetic provider evidence reported a recipient-side rejection.',
        correlationRef: 'PRV-ETHSWIFT-20240610-3302',
      },
      {
        id: 'tl-007-3',
        timestamp: '2024-06-10T13:18:00Z',
        category: 'samra_canonical',
        label: 'Funding Refunded',
        detail: 'Samra canonical ledger recorded a synthetic refund and matched reconciliation.',
      },
    ],
  },
];

// ─── Money Flows ──────────────────────────────────────────────────────────────

export const MONEY_FLOWS: MoneyFlow[] = TRANSFERS.map((t) => ({
  transferId: t.id,
  reference: t.reference,
  currentStage:
    t.status === 'completed' || t.status === 'reversed'
      ? 'reconciliation'
      : t.status === 'failed' || t.status === 'timed_out'
      ? 'failed'
      : t.status === 'reconciliation_exception'
      ? 'reconciliation'
      : 'payout',
  stages: [
    {
      stage: 'initiation',
      label: 'Initiation',
      status:
        ['completed', 'pending', 'failed', 'refunded', 'reversed', 'timed_out', 'reconciliation_exception'].includes(t.status)
          ? 'complete'
          : 'active',
      enteredAt: t.createdAt,
      exitedAt: t.createdAt,
      durationMs: 500,
      money: t.sendAmount,
      correlationId: t.reference,
      attempt: 1,
      evidenceSource: 'Samra canonical state',
    },
    {
      stage: 'funding',
      label: 'Funding Capture',
      status: t.fundingState === 'refunded' ? 'failed' : ['captured', 'settled'].includes(t.fundingState) ? 'complete' : 'pending',
      enteredAt: t.createdAt,
      exitedAt: t.fundingState !== 'awaiting' ? t.updatedAt : undefined,
      durationMs: t.fundingState !== 'awaiting' ? 45000 : undefined,
      money: t.sendAmount,
      correlationId: `HOLD-${t.reference}`,
      attempt: 1,
      evidenceSource: 'Samra canonical state',
    },
    {
      stage: 'payout',
      label: 'Provider Payout',
      status:
        t.payoutState === 'failed' || t.payoutState === 'reversed'
          ? 'failed'
          : t.payoutState === 'delivered'
          ? 'complete'
          : t.payoutState === 'processing'
          ? 'active'
          : t.fundingState === 'awaiting'
          ? 'pending'
          : 'pending',
      enteredAt: t.fundingState !== 'awaiting' ? t.updatedAt : undefined,
      exitedAt: t.payoutState === 'delivered' || t.payoutState === 'failed' ? t.updatedAt : undefined,
      durationMs: t.payoutState === 'delivered' ? 570000 : undefined,
      money: t.receiveAmount,
      correlationId: t.providerCorrelationRef ?? t.providerRef,
      attempt: t.status === 'failed' ? 3 : t.status === 'pending' ? 2 : 1,
      lastError: t.status === 'failed' ? 'Synthetic provider rejection: destination reference invalid.' : undefined,
      nextRetryAt: t.status === 'pending' ? '2024-06-14T10:00:00Z' : undefined,
      evidenceSource: 'Provider-reported evidence',
    },
    {
      stage: 'reconciliation',
      label: 'Reconciliation',
      status:
        t.reconciliationState === 'matched'
          ? 'complete'
          : t.reconciliationState === 'exception'
          ? 'failed'
          : t.reconciliationState === 'skipped'
          ? 'skipped'
          : t.payoutState === 'delivered'
          ? 'active'
          : 'pending',
      enteredAt: t.completedAt,
      exitedAt: t.reconciliationState === 'matched' ? t.updatedAt : undefined,
      durationMs: t.reconciliationState === 'matched' ? 5000 : undefined,
      note:
        t.reconciliationState === 'exception'
          ? 'Amount mismatch detected — see reconciliation exceptions.'
          : undefined,
      money: t.receiveAmount,
      correlationId: `RECON-${t.reference}`,
      attempt: 1,
      evidenceSource: 'Samra canonical state',
    },
  ],
}));

// ─── Reconciliation ───────────────────────────────────────────────────────────

export const RECONCILIATION_RUNS: ReconciliationRun[] = [
  {
    id: 'recon-001',
    reference: 'RECON-20240614-AM',
    startedAt: '2024-06-14T06:00:00Z',
    completedAt: '2024-06-14T06:08:12Z',
    status: 'completed',
    totalRecords: 487,
    matchedRecords: 481,
    exceptionCount: 6,
    provider: 'EthSwift',
    exceptions: [
      {
        id: 'ex-001',
        runId: 'recon-001',
        transferId: 'txn-004',
        transferRef: 'TXN-20240612-041',
        exceptionType: 'amount_mismatch',
        samraValue: { amount: '41,250.00', currency: 'ETB' },
        providerValue: { amount: '41,000.00', currency: 'ETB' },
        raisedAt: '2024-06-14T06:05:30Z',
        notes: 'Provider settlement short by ETB 250.00. Pending provider investigation.',
      },
      {
        id: 'ex-002',
        runId: 'recon-001',
        transferId: undefined,
        transferRef: 'TXN-20240613-077',
        exceptionType: 'missing_provider_record',
        samraValue: { amount: '820.00', currency: 'USD' },
        providerValue: undefined,
        raisedAt: '2024-06-14T06:06:00Z',
        notes: 'No matching provider record found for this Samra transfer.',
      },
    ],
  },
  {
    id: 'recon-002',
    reference: 'RECON-20240613-PM',
    startedAt: '2024-06-13T18:00:00Z',
    completedAt: '2024-06-13T18:06:44Z',
    status: 'completed',
    totalRecords: 512,
    matchedRecords: 512,
    exceptionCount: 0,
    provider: 'EthSwift',
    exceptions: [],
  },
  {
    id: 'recon-003',
    reference: 'RECON-20240614-PM',
    startedAt: '2024-06-14T18:00:00Z',
    completedAt: undefined,
    status: 'running',
    totalRecords: 203,
    matchedRecords: 198,
    exceptionCount: 1,
    provider: 'EthSwift',
    exceptions: [
      {
        id: 'ex-003',
        runId: 'recon-003',
        transferRef: 'TXN-20240614-042',
        exceptionType: 'timing_gap',
        samraValue: { amount: '600.00', currency: 'USD' },
        raisedAt: '2024-06-14T18:04:00Z',
        notes: 'Transfer completed but provider settlement timestamp is 47 minutes after Samra close.',
      },
    ],
  },
];

// ─── Workers ──────────────────────────────────────────────────────────────────

export const WORKER_JOBS: WorkerJob[] = [
  {
    id: 'wrk-9921',
    queue: 'payout-delivery',
    jobType: 'DeliverPayout',
    status: 'completed',
    attempt: 1,
    maxAttempts: 3,
    enqueuedAt: '2024-06-14T08:01:10Z',
    startedAt: '2024-06-14T08:01:12Z',
    completedAt: '2024-06-14T08:12:30Z',
    latencyMs: 678000,
    payload: { transferId: 'txn-001', provider: 'EthSwift' },
  },
  {
    id: 'wrk-9922',
    queue: 'payout-delivery',
    jobType: 'DeliverPayout',
    status: 'running',
    attempt: 1,
    maxAttempts: 3,
    leaseExpiresAt: '2024-06-14T10:10:00Z',
    enqueuedAt: '2024-06-14T09:32:00Z',
    startedAt: '2024-06-14T09:32:05Z',
    payload: { transferId: 'txn-002', provider: 'EthSwift' },
  },
  {
    id: 'wrk-9903',
    queue: 'payout-delivery',
    jobType: 'DeliverPayout',
    status: 'failed',
    attempt: 3,
    maxAttempts: 3,
    enqueuedAt: '2024-06-13T14:01:00Z',
    startedAt: '2024-06-13T14:01:05Z',
    completedAt: '2024-06-13T14:04:00Z',
    latencyMs: 175000,
    errorMessage: 'Provider returned 422: ACCT_NOT_FOUND after 3 attempts.',
    payload: { transferId: 'txn-003', provider: 'EthSwift' },
  },
  {
    id: 'wrk-9880',
    queue: 'reconciliation',
    jobType: 'RunReconciliation',
    status: 'completed',
    attempt: 1,
    maxAttempts: 1,
    enqueuedAt: '2024-06-14T06:00:00Z',
    startedAt: '2024-06-14T06:00:02Z',
    completedAt: '2024-06-14T06:08:12Z',
    latencyMs: 490000,
    payload: { runId: 'recon-001', provider: 'EthSwift' },
  },
  {
    id: 'wrk-9923',
    queue: 'reconciliation',
    jobType: 'RunReconciliation',
    status: 'running',
    attempt: 1,
    maxAttempts: 1,
    leaseExpiresAt: '2024-06-14T18:30:00Z',
    enqueuedAt: '2024-06-14T18:00:00Z',
    startedAt: '2024-06-14T18:00:02Z',
    payload: { runId: 'recon-003', provider: 'EthSwift' },
  },
  {
    id: 'wrk-9850',
    queue: 'payout-delivery',
    jobType: 'DeliverPayout',
    status: 'retrying',
    attempt: 2,
    maxAttempts: 3,
    enqueuedAt: '2024-06-14T07:00:00Z',
    startedAt: '2024-06-14T07:00:10Z',
    errorMessage: 'Provider timeout on attempt 1. Retrying in 60s.',
    payload: { transferId: 'txn-005', provider: 'EthSwift' },
  },
  {
    id: 'wrk-9810',
    queue: 'payout-delivery',
    jobType: 'DeliverPayout',
    status: 'lease_expired',
    attempt: 1,
    maxAttempts: 3,
    leaseExpiresAt: '2024-06-14T05:30:00Z',
    enqueuedAt: '2024-06-14T05:00:00Z',
    startedAt: '2024-06-14T05:00:05Z',
    errorMessage: 'Worker lease expired without acknowledgement.',
    payload: { transferId: 'txn-005', provider: 'EthSwift' },
  },
  {
    id: 'wrk-9924',
    queue: 'notifications',
    jobType: 'SendCompletionNotification',
    status: 'queued',
    attempt: 0,
    maxAttempts: 2,
    enqueuedAt: '2024-06-14T09:55:00Z',
    payload: { transferId: 'txn-002', channel: 'email' },
  },
];

// ─── Audit Events ─────────────────────────────────────────────────────────────

export const AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'aud-001',
    timestamp: '2024-06-14T08:00:00Z',
    category: 'transfer',
    action: 'transfer.created',
    actorId: 'cust-001',
    actorType: 'user',
    resourceType: 'Transfer',
    resourceId: 'txn-001',
    detail: { reference: 'TXN-20240614-001', amount: '500.00', currency: 'USD' },
    immutable: true,
  },
  {
    id: 'aud-002',
    timestamp: '2024-06-14T08:12:30Z',
    category: 'transfer',
    action: 'transfer.completed',
    actorId: 'svc-payout-worker',
    actorType: 'service',
    resourceType: 'Transfer',
    resourceId: 'txn-001',
    detail: { providerRef: 'PRV-ETHSWIFT-20240614-7821', deliveredAmount: '27500.00' },
    immutable: true,
  },
  {
    id: 'aud-003',
    timestamp: '2024-06-14T06:00:00Z',
    category: 'reconciliation',
    action: 'reconciliation.run.started',
    actorId: 'svc-reconciliation',
    actorType: 'service',
    resourceType: 'ReconciliationRun',
    resourceId: 'recon-001',
    detail: { provider: 'EthSwift', recordsCount: 487 },
    immutable: true,
  },
  {
    id: 'aud-004',
    timestamp: '2024-06-14T06:08:12Z',
    category: 'reconciliation',
    action: 'reconciliation.run.completed',
    actorId: 'svc-reconciliation',
    actorType: 'service',
    resourceType: 'ReconciliationRun',
    resourceId: 'recon-001',
    detail: { matched: 481, exceptions: 6 },
    immutable: true,
  },
  {
    id: 'aud-005',
    timestamp: '2024-06-13T14:00:00Z',
    category: 'transfer',
    action: 'transfer.created',
    actorId: 'cust-001',
    actorType: 'user',
    resourceType: 'Transfer',
    resourceId: 'txn-003',
    detail: { reference: 'TXN-20240613-089', amount: '250.00', currency: 'USD' },
    immutable: true,
  },
  {
    id: 'aud-006',
    timestamp: '2024-06-13T14:08:00Z',
    category: 'transfer',
    action: 'transfer.failed',
    actorId: 'svc-payout-worker',
    actorType: 'worker',
    resourceType: 'Transfer',
    resourceId: 'txn-003',
    detail: { reason: 'ACCT_NOT_FOUND', providerRef: 'PRV-ETHSWIFT-20240613-6601' },
    immutable: true,
  },
  {
    id: 'aud-007',
    timestamp: '2024-06-11T11:30:00Z',
    category: 'admin',
    action: 'transfer.reversal.requested',
    actorId: 'ops-operator-001',
    actorType: 'user',
    resourceType: 'Transfer',
    resourceId: 'txn-006',
    detail: { reason: 'Customer request — duplicate send.', commandRef: 'CMD-REV-2024-00041' },
    immutable: true,
  },
  {
    id: 'aud-008',
    timestamp: '2024-06-14T09:30:00Z',
    category: 'transfer',
    action: 'transfer.created',
    actorId: 'cust-003',
    actorType: 'user',
    resourceType: 'Transfer',
    resourceId: 'txn-002',
    detail: { reference: 'TXN-20240614-002', amount: '1200.00', currency: 'USD' },
    immutable: true,
  },
  {
    id: 'aud-009',
    timestamp: '2024-06-14T02:00:00Z',
    category: 'auth',
    action: 'ops.user.login',
    actorId: 'ops-operator-001',
    actorType: 'user',
    detail: { portal: 'ops', mfaMethod: 'totp' },
    immutable: true,
  },
  {
    id: 'aud-010',
    timestamp: '2024-06-12T11:18:00Z',
    category: 'reconciliation',
    action: 'reconciliation.exception.raised',
    actorId: 'svc-reconciliation',
    actorType: 'service',
    resourceType: 'ReconciliationException',
    resourceId: 'ex-001',
    detail: { transferRef: 'TXN-20240612-041', exceptionType: 'amount_mismatch' },
    immutable: true,
  },
];

// ─── System Health ────────────────────────────────────────────────────────────

export const SYSTEM_HEALTH: SystemHealth = {
  overallStatus: 'degraded',
  checkedAt: '2024-06-14T10:00:00Z',
  signals: [
    {
      component: 'API Gateway',
      category: 'api',
      status: 'healthy',
      latencyMs: 34,
      lastCheckedAt: '2024-06-14T10:00:00Z',
    },
    {
      component: 'Primary Ledger DB',
      category: 'database',
      status: 'healthy',
      latencyMs: 8,
      lastCheckedAt: '2024-06-14T10:00:00Z',
    },
    {
      component: 'Read Replica DB',
      category: 'database',
      status: 'degraded',
      latencyMs: 420,
      lastCheckedAt: '2024-06-14T10:00:00Z',
      message: 'Replication lag 4.2s above threshold.',
    },
    {
      component: 'Payout Worker Pool',
      category: 'worker',
      status: 'healthy',
      latencyMs: 12,
      lastCheckedAt: '2024-06-14T10:00:00Z',
    },
    {
      component: 'Reconciliation Worker',
      category: 'worker',
      status: 'healthy',
      latencyMs: 20,
      lastCheckedAt: '2024-06-14T10:00:00Z',
    },
    {
      component: 'EthSwift Provider',
      category: 'provider',
      status: 'healthy',
      latencyMs: 210,
      lastCheckedAt: '2024-06-14T09:58:00Z',
    },
    {
      component: 'Redis Cache',
      category: 'cache',
      status: 'healthy',
      latencyMs: 3,
      lastCheckedAt: '2024-06-14T10:00:00Z',
    },
    {
      component: 'Notification Service',
      category: 'api',
      status: 'down',
      lastCheckedAt: '2024-06-14T09:55:00Z',
      message: 'Service unreachable. Last successful ping 9:48 UTC.',
    },
  ],
};

// ─── Reports ──────────────────────────────────────────────────────────────────

export const AGGREGATE_REPORTS: AggregateReport[] = [
  {
    id: 'rpt-001',
    title: 'Daily Operations Summary',
    period: '2024-06-14',
    generatedAt: '2024-06-14T09:00:00Z',
    sections: [
      {
        title: 'Transfer Volume',
        metrics: [
          { source: 'ledger', label: 'Total Initiated', value: '2,391', unit: 'transfers' },
          { source: 'ledger', label: 'Total Volume', value: '4,821,330.00', unit: 'USD' },
          { source: 'ledger', label: 'Completed', value: '2,347', unit: 'transfers' },
          { source: 'ledger', label: 'Failed', value: '43', unit: 'transfers' },
          { source: 'ledger', label: 'Timed Out', value: '1', unit: 'transfers' },
        ],
      },
      {
        title: 'Reconciliation',
        metrics: [
          { source: 'ledger', label: 'Runs Completed', value: '2', unit: 'runs' },
          { source: 'ledger', label: 'Records Processed', value: '999', unit: 'records' },
          { source: 'ledger', label: 'Matched', value: '993', unit: 'records' },
          { source: 'ledger', label: 'Exceptions', value: '6', unit: 'open' },
        ],
      },
      {
        title: 'Provider Performance',
        metrics: [
          { source: 'provider', label: 'EthSwift Success Rate', value: '98.2', unit: '%' },
          { source: 'provider', label: 'EthSwift Avg Delivery', value: '9.4', unit: 'min' },
          { source: 'provider', label: 'Settlement Pending', value: '182,400.00', unit: 'USD' },
        ],
      },
    ],
  },
  {
    id: 'rpt-002',
    title: 'Weekly Operations Summary',
    period: '2024-06-08 – 2024-06-14',
    generatedAt: '2024-06-14T06:00:00Z',
    sections: [
      {
        title: 'Transfer Volume',
        metrics: [
          { source: 'ledger', label: 'Total Initiated', value: '16,244', unit: 'transfers' },
          { source: 'ledger', label: 'Total Volume', value: '31,820,400.00', unit: 'USD' },
          { source: 'ledger', label: 'Completed', value: '15,987', unit: 'transfers' },
          { source: 'ledger', label: 'Failed', value: '257', unit: 'transfers' },
        ],
      },
      {
        title: 'Reconciliation',
        metrics: [
          { source: 'ledger', label: 'Runs Completed', value: '14', unit: 'runs' },
          { source: 'ledger', label: 'Total Exceptions', value: '23', unit: 'open' },
        ],
      },
    ],
  },
];
