# syntax=docker/dockerfile:1.7@sha256:a57df69d0ea827fb7266491f2813635de6f17269be881f696fbfdf2d83dda33e
FROM node:25-bookworm-slim@sha256:81db02c4b671288a03915da9534dbd54f96d0e7c24d80ccc54f5b36b2e684370

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
WORKDIR /workspace

RUN corepack enable
COPY . .
RUN pnpm install --frozen-lockfile --prod --filter @workspace/db... \
  && rm -rf /pnpm/store /root/.cache/pnpm

ENV NODE_ENV=production
WORKDIR /workspace/lib/db
USER node
CMD ["node", "./node_modules/drizzle-kit/bin.cjs", "migrate", "--config", "./drizzle.config.ts"]
